<?php
// auto-generated by sfPropelCrud
// date: 2008/04/21 22:32:09
?>
<?php use_helper('Object') ?>

<?php echo form_tag('sfPhotoGallery/create') ?>

<?php echo input_hidden_tag('table',$sf_request->getParameter('table')) ?>
<?php echo input_hidden_tag('table_id',$sf_request->getParameter('table_id')) ?>

<table>
<tbody>


<tr>
  <th>Titolo della foto:</th>
  <td><?php echo object_input_tag($photo, 'getTitle', array (
  'size' => 30,
)) ?></td>
</tr>
<tr>
  <th>Descrizione della foto:</th>
  <td><?php echo object_textarea_tag($photo, 'getDescription', array (
  'size' => '30x4',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('Aggiungi la foto') ?>
</form>
