<?php
// auto-generated by sfPropelCrud
// date: 2008/04/21 22:32:09
?>
<h1>photo</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Entity</th>
  <th>Entity</th>
  <th>Name</th>
  <th>Title</th>
  <th>Description</th>
</tr>
</thead>
<tbody>
<?php foreach ($photos as $photo): ?>
<tr>
    <td><?php echo link_to($photo->getId(), 'photo/show?id='.$photo->getId()) ?></td>
      <td><?php echo $photo->getEntity() ?></td>
      <td><?php echo $photo->getEntityId() ?></td>
      <td><?php echo $photo->getName() ?></td>
      <td><?php echo $photo->getTitle() ?></td>
      <td><?php echo $photo->getDescription() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'photo/create') ?>
